name: Daily Case Scraper

on:
  schedule:
    # Run every 6 hours
    - cron: '0 */6 * * *'
  workflow_dispatch: # Allow manual trigger
    inputs:
      debug:
        description: 'Run in debug mode'
        required: false
        default: 'false'

jobs:
  scrape-and-process:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Create data directories
      run: |
        mkdir -p data/raw
        mkdir -p data/cases
        mkdir -p public/data
    
    - name: Run scraper
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}
      run: npm run scrape
      continue-on-error: true
    
    - name: Run summarizer
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}
      run: npm run summarize
      if: success() || failure()
    
    - name: Build indexes
      run: npm run build-index
      if: success() || failure()
    
    - name: Commit and push changes
      run: |
        git config user.name "5MC Bot"
        git config user.email "bot@5mincase.com"
        git add data/
        git add public/data/
        git diff --staged --quiet || git commit -m "📚 Update cases $(date +'%Y-%m-%d %H:%M')"
        git push
      if: success() || failure()
    
    - name: Trigger deployment
      uses: actions/github-script@v7
      with:
        script: |
          // Vercel will auto-deploy on push
          console.log('Changes pushed - Vercel will auto-deploy')
    
    - name: Send notification (on failure)
      if: failure()
      uses: actions/github-script@v7
      with:
        script: |
          const issue = await github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: `Case scraper failed - ${new Date().toISOString()}`,
            body: `The daily case scraper workflow failed. Check the [workflow run](${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}) for details.`
          })
